### ISSUE TITLE
plot volume or aggregated sentiment

### ISSUE THREAD

**Issue by bkj** [gophronesis/penny-sae#113]

**Comment by MorganPeterson** [comment]
This has been implemented on mp-030-toggle-volume-sentiment. It still has bugs that need to be worked out before being merged into dev.

Remaining tasks (not complete):
- [ ] set threshold for what qualifies as negative, neutral or positive
- [ ] fix bug that does not render price/volume charts if there are no posts of a certain sentiment
- [ ] set it so brush does not reset if you choose a different sentiment
- [ ] test free text search
- [ ] lots of testing

**Comment by MorganPeterson** [comment]
I think I am going to have to leave that the brush resets when sentiments are toggled. The brushing function is to embedded inside the draw function that to remove it would require a huge refactoring of the code.
