### ISSUE TITLE
Uncaught TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by MorganPeterson** [gophronesis/penny-sae#32]
To reproduce:
1. search for company
2. select company
3. select network analysis
4. scroll down to and select 'List Associates of [company you selected]
5. select any of the 'Links' links

In associates.js:95, error starts in show_links_ner(), but the problem appears to be in the call to ES in networks.js:52, add_node() makes a call to initElasticBig(), but that function never calls it's callback function which is responsible for setting several variables.

**Comment by bkj** [comment]
Not relevant anymore
