### ISSUE TITLE
Input Widgets

### ISSUE THREAD

**Issue by bkj** [gophronesis/penny-sae#46]
Edit the "red flag" parameterization to accept the following parameters

```
        "symbology" : {
            "field"     : "name", (dropdown)
            "min_date"  : "2000-01-01", (date picker)
            "max_date"  : "2016-01-01", (date picker)
            "threshold" : 1 (numeric entry box, integer)
        },
        "network" : {
            "number_of_neighbors" : range slider (so pick bottom and upper bound, like Geofin date slider)
            "percent_otc" : integer between 0 and 100
        },
        "financials" : {
            "type"         : "revenues", (dropdown with random choices for now)
            "min_date" : date picker
            "max_date" : date picker
            "value" : range slider (pick bottom and upper bound)
            "threshold" : numeric entry box, integer
        },
        "trading_halts" : {
            "min_date" : date picker
            "max_date" : date picker
            "threshold" : 1
        },
        "delinquency" : {
            "form"      : "10-K", (dropdown, random choices for now)
            "min_date"  : "2000-01-01", (date picker)
            "max_date"  : "2016-01-01", (date picker)
            "threshold" : 1 (numeric entry box, integer)
        }
    },

```

Ignore `pv` and `crowdsar` for now.  Ask questions if any of these are unclear.

**Comment by MorganPeterson** [comment]
Completed and waiting for merge.

**Comment by bkj** [comment]
- [ ] Trying to use the datepicker closes the dropdown
- [ ] CSS of datepicker is unuseable -- buttons and labels are invisible

**Comment by MorganPeterson** [comment]
What is going on with this? I can no longer see my code, widgets are fully disabled, and my branch seems to have been deleted?

**Comment by bkj** [comment]
Which branch?

**Comment by bkj** [comment]
I deleted that branch after the merge, since is was basically done.  I
don't know what you mean by you can't see your code and widgets are fully
disabled

**Comment by MorganPeterson** [comment]
mp-013-widgets

**Comment by bkj** [comment]
I deleted it because it was done -- it was merged and this issue was closed so we didn't need it anymore.  All of the changes are in dev now.

**Comment by MorganPeterson** [comment]
If you click on the customize buttons all I get is an error saying that showParameters does not handle anything.

Searching for the reason now.

**Comment by bkj** [comment]
This bug does not exist at acc15d328d42bad8dbe6c01a90c9e939b6e708cc, so it
has something to do with trying to fix the routing.

**Comment by MorganPeterson** [comment]
Fixed.

It had to do with the way the dropdown menu was being rendered.

**Comment by bkj** [comment]
OK.  Remember that all code on dev should be tested fairly thoroughly,
especially at this point in the game

**Comment by MorganPeterson** [comment]
Using the calendar doesn't close my dropdown at all. I've tested it in 3 browsers and it works.

**Comment by MorganPeterson** [comment]
I see it now. It only does it when I change months. All other functions don't close the calendar.

**Comment by MorganPeterson** [comment]
Moved calendar button images to the dist folder and disabled data-toggling in yamm and replaced it with a custom handler.
