### ISSUE TITLE
Add post detail

### ISSUE THREAD

**Issue by bkj** [gophronesis/penny-sae#50]
Below the price/volume/crowdsar chart, need to add the same charts/displays as in penny:

Post by user over time
Sentiment meter by user
List of actual post body

Probably able to use mostly code from penny for this. Could start developing with random/synthetic data or with real data.

**Comment by bkj** [comment]
@MorganPeterson  This is done, right?

**Comment by MorganPeterson** [comment]
Yes, it is done.

**Comment by bkj** [comment]
- CSS
  - [ ] Red/green bars in `Post Volume` chart are hard to look at
  - [ ] Charts should fill horizontal width if possible
  - [ ] Posts should fill vertical space
  - [ ] Remove duplicate X-axis labels on Post Volume chart
- Functionality
  - [ ] Clicking on users should subset the posts on the right, as in Penny
  - [ ] Y-axis of charts should rescale to the appropriate range, as in Penny 
      - (See `TAUG` if you select 2015 as your time range -- you can't see price information)
  - [ ] OHLC chart is preferable to a line chart.  If OHLC is _impossible_, then smoothing/interpolation on the line chart must be turned off.
  - [ ] Volume should be plotted on log10 scale
  - [ ] List of posts should be sorted by time

**Comment by bkj** [comment]
@MorganPeterson This is top priority

**Comment by MorganPeterson** [comment]
Ohlc isn't impossible, it is just unreadable.

**Comment by bkj** [comment]
Can you show a screenshot as an example?

**Comment by MorganPeterson** [comment]
I will have to reimplement it.

**Comment by bkj** [comment]
You could try taking the smoothing off of the current plot to see if that looks better first

**Comment by MorganPeterson** [comment]
Moving back to candlesticks isn't working for some reason.

How do you turn off the smoothing? The price chart is in techan and I can't
find the documentation for it.

On Fri, Jun 10, 2016 at 2:00 PM, Ben Johnson <notifications@github.com>
wrote:

> You could try taking the smoothing off of the current plot to see if that
> looks better first
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gophronesis/penny-sae/issues/50#issuecomment-225252639>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALO_cqS52uaSPxQl0C7grnJxgNJlYeEOks5qKaZGgaJpZM4IkdHF>
> .
>



-- 
Morgan Peterson
Phronesis

**Comment by bkj** [comment]
I think the apparent smoothing effect is a consequence of only fetching 10 days from the ES index. The query should return all PV data

**Comment by MorganPeterson** [comment]
The charts filling width is obviously not impossible, but I was looking at the way we are handling outlets in the templates and I don't see a good way of doing this without a complete redesign of them.

The problem stems from the detail boxes on the left. The charts will always conflict with them.

One solution I could try is just making the search results width narrower there by making the charts wider, but they still won't fill the screen.

**Comment by MorganPeterson** [comment]
Due to differing render times and not wanting to to re-render charts more than the 2 times they are already rendered, the only way that I can think of making forum posts to fill the screen height is to set an arbitrary height for a wrapper that contains the gauges, time lines, forum charts.

**Comment by MorganPeterson** [comment]
I tried converting the Y-axis to log10 but d3/techan do not have good support for logarithmic values on bar charts and it has been an abject failure so far.

Is there perhaps another way you would like to go with it?

References: https://github.com/dc-js/dc.js/issues/477  &  https://github.com/dc-js/dc.js/issues/646

**Comment by bkj** [comment]
Charts seem to be filling horizontal width appropriately now -- maybe it was just a bug before.  There are a lot of issues with overlapping labels that need to be fixed though.
<img width="904" alt="screen shot 2016-06-13 at 10 51 12 pm" src="https://cloud.githubusercontent.com/assets/6086781/16029768/64b4864c-31b9-11e6-8dee-3b1491da7add.png">

Bottom of these need to be aligned:
<img width="967" alt="screen shot 2016-06-13 at 10 51 22 pm" src="https://cloud.githubusercontent.com/assets/6086781/16029772/6dadf0da-31b9-11e6-8418-3d5e622a0897.png">

Non-log is fine for now.  The other issues are more important and should be addressed first.

**Comment by MorganPeterson** [comment]
I spent quite a few hours today trying to get the gauge charts and the forum posts to line up. I can't figure out how to do it. The gauges and the time lines are sized dynamically and because of async there is no guaranteed time as to when they are fully rendered and what size they will be when they do render making it impossible to use jquery to get the element size and then transfer that measurement to the forum posts.

I tried some CSS tricks but they all failed.

I'm out of ideas on how to line these two up. I need to put it on the backburner because I blew 50% of my day just on this.

**Comment by bkj** [comment]
Just the bottoms need to line up -- you can just set a max height and have
it overflow last that.

**Comment by MorganPeterson** [comment]
For the sake of clarity:

When you say remove the duplicate x axis labels on post volume chart do you mean remove all the x axis labels on the post volume chart?

**Comment by bkj** [comment]
There's date labels on the slider and on the main plot -- don't think we
need both IMO

**Comment by MorganPeterson** [comment]
My only concern with that is that the slider never re-scales so you lose some context on the post volume chart. Maybe I should lose the labels but leave the ticks?

**Comment by bkj** [comment]
Oh yeah that's a good point. Maybe just decrease the number/prominence of
the labels on the slider then

**Comment by bkj** [comment]
- [ ] Bug in "Clicking on users should subset the posts displayed, as in Penny"
   - Go to "http://localhost:8090/#/sidebar/-/detail/0001451512/board"
   - Click "Doc K"
   - No posts appear on RHS

**Comment by MorganPeterson** [comment]
It appears to me, I may be wrong because I didn't manually check all the
posts, that it is missing due to only 1000 entries being loaded from ES and
none of them were posts made by that poster.

On Thu, Jun 16, 2016 at 6:19 PM, Ben Johnson <notifications@github.com>
wrote:

>
>    - Bug in "Clicking on users should subset the posts displayed, as in
>    Penny"
>       - Go to "http://localhost:8090/#/sidebar/-/detail/0001451512/board"
>       - Click "Doc K"
>       - No posts appear on RHS
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gophronesis/penny-sae/issues/50#issuecomment-226630520>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALO_cjv4oN4OqioPyzxI0yjYN20zSfkFks5qMcv3gaJpZM4IkdHF>
> .
>



-- 
Morgan Peterson
Phronesis

**Comment by bkj** [comment]
OK -- we should have clicking a user make a server call to get their posts, and maybe only pull back 100 or so to begin with.

**Comment by MorganPeterson** [comment]
That is what I am working on right at this moment. I hope to have something
up and running tomorrow morning.

On Thu, Jun 16, 2016 at 6:24 PM, Ben Johnson <notifications@github.com>
wrote:

> OK -- we should have clicking a user make a server call to get their
> posts, and maybe only pull back 100 or so to begin with.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gophronesis/penny-sae/issues/50#issuecomment-226631524>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALO_cpA6Twb8fU8k8L5BJqlY3sreIugLks5qMc0TgaJpZM4IkdHF>
> .
>



-- 
Morgan Peterson
Phronesis

**Comment by bkj** [comment]
Ok cool

**Comment by MorganPeterson** [comment]
I think we have integrated as much of this as we can.

If there is more that we think we can do on this checklist, then I think it would be a good idea to open separate issues for each.
