### ISSUE TITLE
Finish network interface

### ISSUE THREAD

**Issue by bkj** [gophronesis/penny-sae#51]
Finish network interface

**Comment by bkj** [comment]
Need to implement `Hide Terminal Nodes` button.  This could be added as a piece of metadata to the `forms` index.

**Comment by bkj** [comment]
`Hide Terminal Nodes` is implemented.  Changing title from "Finish network interface" to "polish network interface", and removing `bug` label.

**Comment by MorganPeterson** [comment]
Switched network interface from jit to d3.
