### ISSUE TITLE
Financials tab

### ISSUE THREAD

**Issue by bkj** [gophronesis/penny-sae#52]
Implement financials tab.

Currently blocked by missing data.

**Comment by MorganPeterson** [comment]
Do we have the data for this, yet?

**Comment by bkj** [comment]
It's coming -- talk to Emmett for details

**Comment by bkj** [comment]
It should be done soon, but if Emmett can upload a temporary dataset in the
correct format, that would let us make forward progress on the frontend
while he irons out some of the data processing kinks

**Comment by MorganPeterson** [comment]
Financial Tab is now implemented, but I am unsure of what fields we would like to be present.

**Comment by bkj** [comment]
Talk to Emmett and resolve -- he'll know which ones are intended for display

**Comment by MorganPeterson** [comment]
Financial Tab is now implemented, but I am unsure of what fields we would
like to be present.

On Tue, Jun 21, 2016 at 10:48 AM, Ben Johnson <notifications@github.com>
wrote:

> Talk to Emmett and resolve -- he'll know which ones are intended for
> display
>
> On Tue, Jun 21, 2016 at 10:45 AM, Morgan Peterson <
> notifications@github.com>
> wrote:
>
> > Financial Tab is now implemented, but I am unsure of what fields we would
> > like to be present.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/gophronesis/penny-sae/issues/52#issuecomment-227462652
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AFzgfWM80KkjqRA78a_is352kXW83oq_ks5qN_j4gaJpZM4IkrO7
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/gophronesis/penny-sae/issues/52#issuecomment-227463874>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALO_ckYsm0UQPCEzKp76cmGHG_l_60sYks5qN_nTgaJpZM4IkrO7>
> .
>



-- 
Morgan Peterson
Phronesis

**Comment by Emmett-Culhane** [comment]
assets, liabilities, stockholders equity

net income, operating income,

earnings, cash, revenues

assets current, liabilities current,

commonStockSharesOutstanding


--- then if you want

interest expense, operating expense

profit, accounts payable, depreciation and amortization

**Comment by Emmett-Culhane** [comment]
and also a definite one, though it is a little repetitive is
'liabilitiesAndStockholdersEquity'

**Comment by MorganPeterson** [comment]
That will make for a very large table.

Is there an order of preference?

Do you know a CIK off the top of your head that has those fields populated
for testing? I haven't seen one, yet.

On Tue, Jun 21, 2016 at 11:02 AM, Emmett-Culhane <notifications@github.com>
wrote:

> and also a definite one, though it is a little repetitive is
> 'liabilitiesAndStockholdersEquity'
>
> On Tue, Jun 21, 2016 at 11:02 AM, Emmett Culhane <emmett@gophronesis.com>
> wrote:
>
> > assets, liabilities, stockholders equity
> >
> > net income, operating income,
> >
> > earnings, cash, revenues
> >
> > assets current, liabilities current,
> >
> > commonStockSharesOutstanding
> >
> >
> > --- then if you want
> >
> > interest expense, operating expense
> >
> > profit, accounts payable, depreciation and amortization
> >
> >
> >
> >
> >
> >
> >
> >
> > On Tue, Jun 21, 2016 at 10:50 AM, Morgan Peterson <
> > notifications@github.com> wrote:
> >
> >> Financial Tab is now implemented, but I am unsure of what fields we
> would
> >> like to be present.
> >>
> >> On Tue, Jun 21, 2016 at 10:48 AM, Ben Johnson <notifications@github.com
> >
> >> wrote:
> >>
> >> > Talk to Emmett and resolve -- he'll know which ones are intended for
> >> > display
> >> >
> >> > On Tue, Jun 21, 2016 at 10:45 AM, Morgan Peterson <
> >> > notifications@github.com>
> >> > wrote:
> >> >
> >> > > Financial Tab is now implemented, but I am unsure of what fields we
> >> would
> >> > > like to be present.
> >> > >
> >> > > —
> >> > > You are receiving this because you authored the thread.
> >> > > Reply to this email directly, view it on GitHub
> >> > > <
> >> >
> >>
> https://github.com/gophronesis/penny-sae/issues/52#issuecomment-227462652
> >> > >,
> >> > > or mute the thread
> >> > > <
> >> >
> >>
> https://github.com/notifications/unsubscribe/AFzgfWM80KkjqRA78a_is352kXW83oq_ks5qN_j4gaJpZM4IkrO7
> >> > >
> >> > > .
> >> > >
> >> >
> >> > —
> >> > You are receiving this because you commented.
> >> > Reply to this email directly, view it on GitHub
> >> > <
> >>
> https://github.com/gophronesis/penny-sae/issues/52#issuecomment-227463874
> >> >,
> >> > or mute the thread
> >> > <
> >>
> https://github.com/notifications/unsubscribe/ALO_ckYsm0UQPCEzKp76cmGHG_l_60sYks5qN_nTgaJpZM4IkrO7
> >> >
> >> > .
> >> >
> >>
> >>
> >>
> >> --
> >> Morgan Peterson
> >> Phronesis
> >>
> >> —
> >> You are receiving this because you are subscribed to this thread.
> >> Reply to this email directly, view it on GitHub
> >> <
> https://github.com/gophronesis/penny-sae/issues/52#issuecomment-227464288
> >,
> >> or mute the thread
> >> <
> https://github.com/notifications/unsubscribe/AOj0ayI_6Rfe_gmQg3l6Em17vxEpKxVmks5qN_oegaJpZM4IkrO7
> >
> >> .
> >>
> >
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/gophronesis/penny-sae/issues/52#issuecomment-227468501>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALO_cpy0XOhsWlm7qluLTINLrfE9CwaYks5qN_0YgaJpZM4IkrO7>
> .
>



-- 
Morgan Peterson
Phronesis

**Comment by Emmett-Culhane** [comment]
I have only half of 2013 and half of 2011. There was a typo in the cmd line
args for the ingest shell so I just loaded all the docs for 2012 through
April. There are a maximum of 4 filings (legitimate annual / quarterly
financials) for a given company in a year. We do not have the range of docs
to provide historical financials for a given company, but plenty of single
period filings. Things will get a lot better now as more documents are
coming in.
