### ISSUE TITLE
Price/Volume tab

### ISSUE THREAD

**Issue by bkj** [gophronesis/penny-sae#53]
Right now, putting fake data into the CROWDSAR field.  (attn @MorganPeterson)  Need to actually hook this into the appropriate CROWDSAR index.

- [ ] Add real CROWDSAR data

**Comment by bkj** [comment]
This looks good. 

Some minor things, probably not the biggest concerns right now, but:

- [ ] Can we change the location of the "Post Volume" and "Price" windows to make consistent w/ original Penny app?
- [ ] Overlapping x-axis labels on by-user charts
- [ ] CSS on post view (should go all the way to the bottom, subtle background color on charts to visually distinguish them from each other, individual posts should not scroll -- maybe you should be able to click on them to see the whole thing?)

**Comment by MorganPeterson** [comment]
There is a ton of issues right now and a lot of what you see will change. I
will keep these points in mind.

On Mon, Jun 6, 2016 at 2:04 PM, Ben Johnson <notifications@github.com>
wrote:

> This looks good.
>
> Some minor things, probably not the biggest concerns right now, but:
>
>    - Can we change the location of the "Post Volume" and "Price" windows
>    to make consistent w/ original Penny app?
>    - Overlapping x-axis labels on by-user charts
>    - CSS on post view (should go all the way to the bottom, subtle
>    background color on charts to visually distinguish them from each other,
>    individual posts should not scroll -- maybe you should be able to click on
>    them to see the whole thing?)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gophronesis/penny-sae/issues/53#issuecomment-224039005>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALO_cjwKAKWVUsDQVOx3wgMpzqxOjR6yks5qJGE6gaJpZM4IkrSr>
> .
>



-- 
Morgan Peterson
Phronesis

**Comment by MorganPeterson** [comment]
I changed the view this morning. I changed the price chart from canlestick
to close due to the candlesticks being too small to read. Plus, I moved the
price from the right side to the left side.

On Mon, Jun 6, 2016 at 2:06 PM, Morgan Peterson <morgan@gophronesis.com>
wrote:

> There is a ton of issues right now and a lot of what you see will change.
> I will keep these points in mind.
>
> On Mon, Jun 6, 2016 at 2:04 PM, Ben Johnson <notifications@github.com>
> wrote:
>
>> This looks good.
>>
>> Some minor things, probably not the biggest concerns right now, but:
>>
>>    - Can we change the location of the "Post Volume" and "Price" windows
>>    to make consistent w/ original Penny app?
>>    - Overlapping x-axis labels on by-user charts
>>    - CSS on post view (should go all the way to the bottom, subtle
>>    background color on charts to visually distinguish them from each other,
>>    individual posts should not scroll -- maybe you should be able to click on
>>    them to see the whole thing?)
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/gophronesis/penny-sae/issues/53#issuecomment-224039005>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ALO_cjwKAKWVUsDQVOx3wgMpzqxOjR6yks5qJGE6gaJpZM4IkrSr>
>> .
>>
>
>
>
> --
> Morgan Peterson
> Phronesis
>



-- 
Morgan Peterson
Phronesis

**Comment by bkj** [comment]
Price and trade volume should be together, as they're naturally paired.  I
don't mind getting rid of candlestick too much.  Can make charts bigger if
necessary / possible.

**Comment by MorganPeterson** [comment]
I merged and pushed this to dev.

This work is finished, but there are still some small issues that will need to be addressed. I am going to close this issue and open separate issues for them.
