### ISSUE TITLE
Node server not printing errors

### ISSUE THREAD

**Issue by bkj** [gophronesis/penny-sae#56]
For some reason, the Node server is not `console.log`ing errors.  Should track this down.

**Comment by MorganPeterson** [comment]
What kind of errors is it not writing out?

I know that the routes don't have an error handling which I have been working on while working on charts.

**Comment by bkj** [comment]
Usually if you do something like reference a variable that doesn't exist it
raises an error and the worker it was on dies and a new one is spawned.
But (at least in network.js) I can reference variables that aren't defined
inside of a function and it doesn't do anything, it just hangs

**Comment by MorganPeterson** [comment]
I know that when ES was slow I have hanging problems inside the fetch and fetch_data methods. That may be a good first place to look.

**Comment by bkj** [comment]
It's not the hanging thats the issue it's that it doesn't seem to be
raising "variable not defined" errors etc

**Comment by bkj** [comment]
Had to add `.catch(function(err) {console.log(err.stack)}` after all of the `client.search(...).then(...)` calls.

I feel like I haven't had to do this to show errors in the past, but whatever, seems to be printing errors for now.
