### ISSUE TITLE
Sidebar does not render

### ISSUE THREAD

**Issue by MorganPeterson** [gophronesis/penny-sae#65]
Sidebar connectOutlet error. Template does not render unless you refresh page.

This has something to do with the outlet element not getting into the DOM at the right time.

**Comment by bkj** [comment]
What are the steps to reproduce this?

**Comment by MorganPeterson** [comment]
1. login
2. in front page search for anything

**Comment by bkj** [comment]
Ah yeah.  Presumably this has to do with the `/login` fix?

**Comment by MorganPeterson** [comment]
I has existed before this except it was with frontpage before the login fix. There is a render call that is either being made and shouldn't or should be called but isn't. It has been a difficult bug to hunt.

**Comment by MorganPeterson** [comment]
This bug seems to have been fixed, but I am going to leave it open for awhile until I am sure.
