### ISSUE TITLE
Frontpage checkboxes disappeared

### ISSUE THREAD

**Issue by bkj** [gophronesis/penny-sae#74]
Check boxes on front page have disappeared -- I notice that the `logout` button got changed, perhaps that is related

**Comment by MorganPeterson** [comment]
That is my mistake. I thought I had gotten rid of all font-awesome references. I will fix this now. Should only take a few minutes.

**Comment by MorganPeterson** [comment]
Font awesome restored. Merged into dev. You will have to pull and run `grunt css.`
