### ISSUE TITLE
Gauges "jump" when you make a selection

### ISSUE THREAD

**Issue by bkj** [gophronesis/penny-sae#75]
1) Open the page
2) Select a time range
3) Gauges "jump" to the other side of the page (and one gets stuck in the middle)

<img width="1440" alt="screen shot 2016-06-21 at 12 16 32 pm" src="https://cloud.githubusercontent.com/assets/6086781/16237352/10d84850-37aa-11e6-8876-125f5cf28cde.png">

**Comment by MorganPeterson** [comment]
That is an old issue that I thought I had taken care of. It no longer does
it on my machine. Try re-running grunt devApp and devLib?

On Tue, Jun 21, 2016 at 12:18 PM, Ben Johnson <notifications@github.com>
wrote:

> 1) Open the page
> 2) Select a time range
> 3) Gauges "jump" to the other side of the page (and one gets stuck in the
> middle)
>
> [image: screen shot 2016-06-21 at 12 16 32 pm]
> <https://cloud.githubusercontent.com/assets/6086781/16237352/10d84850-37aa-11e6-8876-125f5cf28cde.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gophronesis/penny-sae/issues/75>, or mute the thread
> <https://github.com/notifications/unsubscribe/ALO_clX9uH6CIvi5CVWDV-C-5NHEY-Cvks5qOA7JgaJpZM4I66uO>
> .
>



-- 
Morgan Peterson
Phronesis

**Comment by bkj** [comment]
Probably not

**Comment by bkj** [comment]
(Will try -- thanks)

**Comment by MorganPeterson** [comment]
Is this still an issue or may I close this?

On Tue, Jun 21, 2016 at 12:34 PM, Ben Johnson <notifications@github.com>
wrote:

> (Will try -- thanks)
>
> On Tue, Jun 21, 2016 at 12:31 PM, Ben Johnson <ben@gophronesis.com> wrote:
>
> > Probably not
> >
> > On Tue, Jun 21, 2016 at 12:19 PM, Morgan Peterson <
> > notifications@github.com> wrote:
> >
> >> That is an old issue that I thought I had taken care of. It no longer
> does
> >> it on my machine. Try re-running grunt devApp and devLib?
> >>
> >> On Tue, Jun 21, 2016 at 12:18 PM, Ben Johnson <notifications@github.com
> >
> >> wrote:
> >>
> >> > 1) Open the page
> >> > 2) Select a time range
> >> > 3) Gauges "jump" to the other side of the page (and one gets stuck in
> >> the
> >> > middle)
> >> >
> >> > [image: screen shot 2016-06-21 at 12 16 32 pm]
> >> > <
> >>
> https://cloud.githubusercontent.com/assets/6086781/16237352/10d84850-37aa-11e6-8876-125f5cf28cde.png
> >> >
> >> >
> >> > —
> >> > You are receiving this because you are subscribed to this thread.
> >> > Reply to this email directly, view it on GitHub
> >> > <https://github.com/gophronesis/penny-sae/issues/75>, or mute the
> >> thread
> >> > <
> >>
> https://github.com/notifications/unsubscribe/ALO_clX9uH6CIvi5CVWDV-C-5NHEY-Cvks5qOA7JgaJpZM4I66uO
> >> >
> >> > .
> >> >
> >>
> >>
> >>
> >> --
> >> Morgan Peterson
> >> Phronesis
> >>
> >> —
> >> You are receiving this because you authored the thread.
> >> Reply to this email directly, view it on GitHub
> >> <
> https://github.com/gophronesis/penny-sae/issues/75#issuecomment-227492608
> >,
> >> or mute the thread
> >> <
> https://github.com/notifications/unsubscribe/AFzgfeHqVCwkiJYRbhTfViuggPPBnJz5ks5qOA8TgaJpZM4I66uO
> >
> >> .
> >>
> >
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/gophronesis/penny-sae/issues/75#issuecomment-227496787>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALO_cpBHKjyZ_5R8tYrUY7OqvKyK_hdpks5qOBKSgaJpZM4I66uO>
> .
>



-- 
Morgan Peterson
Phronesis

**Comment by bkj** [comment]
You can close if you think it's fixed. I haven't had a chance to test but
I'll reopen if necessary
