### ISSUE TITLE
Poster Time Lines

### ISSUE THREAD

**Issue by MorganPeterson** [gophronesis/penny-sae#90]
We should add a way to sort the list of user time line.

Some ideas:

1. Adjust number of posters visible. Currently 10 is the default
2. Sort users by sentiment
3. Sort users by number of posts
4. Sort users by daily max/min/mean

Of course, I am open to comments and new suggestions.

**Comment by bkj** [comment]
Users were definitely interested in adding ability for more interaction here.  In particular, free text search over the message boards and sorting by sentiment or volume.  I don't think that first iterations of those functionalities would be that bad.

**Comment by MorganPeterson** [comment]
- [ ] select number of poster time lines (currently only 10)
- [ ] sort users by sentiment
- [ ] sort users by number of posts
- [ ] sort users by daily max/min/mean
- [ ] free text search of message board posts
