### ISSUE TITLE
Forum Data Gap

### ISSUE THREAD

**Issue by MorganPeterson** [gophronesis/penny-sae#97]
Penny is not showing any data in the boards between dates 12/22/2015 and 01/11/2016. When I check ES for posts in that date range, I get data, but none of that data is appearing in the charts.

Example:

If you look up the charts for ticker HDSI you will see the gap as you will see on all boards. Yet, this message id is in ES: 119370029. If you look at the poster's timeline (user: Greedy G, user_id: 438323) you will see that no data appears on their timeline either.

As a precaution, I ran the scraper to fill that gap and it returned no new ES records from 12/23/2015.

**Comment by bkj** [comment]
Can you find a difference in schema or variable format for that range?

This raises the point that there are other smaller gaps over the past two
years that should be filled if possible.

**Comment by bkj** [comment]
Also December 23 is a Saturday on a long weekend around Christmas, so it's
possible that the site was down or there was actually very low volume.
Something like Jan 4th may be more representative.

**Comment by MorganPeterson** [comment]
The schema versions and variable formats seem to be the same.

**Comment by MorganPeterson** [comment]
I'm running the scraper against 1/20 and that is returning a lot of entries we don't have. That means that there are gaps that still need to be filled with the scrapers.

It still doesn't explain why the timeline is not picking up the data that does exist. Such as all the entries on 12/23 that does exist in ES.

**Comment by bkj** [comment]
Do they still exist on the site? Posts can be deleted, so that's worth
checking.

In general, there's no guarantee of completeness in the data we have. We
could estimate how much is missing, since the ids are sequential (though
deleted posts throw this off somewhat).

**Comment by MorganPeterson** [comment]
I checked three of the posts on the site and they do still exist.

The problem seems to be with the call to ES. Some of the data is there, but
it is not being returned to the timeline. It may have something to do with
the queries themselves. I am looking at that now.

On Wed, Jul 13, 2016 at 11:07 AM, Ben Johnson <notifications@github.com>
wrote:

> Do they still exist on the site? Posts can be deleted, so that's worth
> checking.
>
> In general, there's no guarantee of completeness in the data we have. We
> could estimate how much is missing, since the ids are sequential (though
> deleted posts throw this off somewhat).
>
> On Wednesday, July 13, 2016, Morgan Peterson <notifications@github.com>
> wrote:
>
> > I'm running the scraper against 1/20 and that is returning a lot of
> > entries we don't have. That means that there are gaps that still need to
> be
> > filled with the scrapers.
> >
> > It still doesn't explain why the timeline is not picking up the data that
> > does exist. Such as all the entries on 12/23 that does exist in ES.
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/gophronesis/penny-sae/issues/97#issuecomment-232383563
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AFzgfawNzklb0fwetb8XH-djGYMEix9aks5qVP4SgaJpZM4JLe37
> >
>
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gophronesis/penny-sae/issues/97#issuecomment-232385194>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALO_ch6fS1Q6iZCsrLDafx1Bq4qSeA_3ks5qVP86gaJpZM4JLe37>
> .
>



-- 
Morgan Peterson
Phronesis

**Comment by MorganPeterson** [comment]
In the meantime, I am also going to be running the scrapers to fill the larger gaps that I see.

**Comment by MorganPeterson** [comment]
It seems to have something to do with the date histogram in ES. If I change the interval to 12h instead of 'day', the 12/23 entries appear as 7 in count and 1/11's 1 count vanishes. If I switch it to '1hr', the doc_count on 12/23 goes to 5.

**Comment by bkj** [comment]
Can you post the ES query here?

**Comment by MorganPeterson** [comment]
{
   'query': {
   'constant_score': {
   'filter': {
    'bool': {
      'must': [
                   {'term': {'__meta__.sym.cik': btData.cik}}
                 ]
              }
           }
          }
       },
       'aggs': {
         'board_histogram': {
            'date_histogram': {
               'field': 'time',
               'interval': '12h'
           }
     }
   }
}

**Comment by bkj** [comment]
For HDSI, it looks like there are 22 posts on 2015-12-23, w/ 15 before noon and 7 after, so nothing funny there. 

It looks like the gap starts on the 24th, 

```
POST ernest_crowdsar/_search?search_type=count
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "ticker.cat": "HDSI"
          }
        }
      ]
    }
  },
  "aggs": {
    "NAME": {
      "date_histogram": {
        "field": "time",
        "interval": "day"
      }
    }
  }
}
```
yields
```
...
        {
          "key_as_string": "2015-12-23T00:00:00.000Z",
          "key": 1450828800000,
          "doc_count": 22
        },
        {
          "key_as_string": "2015-12-24T00:00:00.000Z",
          "key": 1450915200000,
          "doc_count": 0
        },
        {
          "key_as_string": "2015-12-25T00:00:00.000Z",
          "key": 1451001600000,
          "doc_count": 0
        },
        {
          "key_as_string": "2015-12-26T00:00:00.000Z",
          "key": 1451088000000,
          "doc_count": 0
        },
        {
          "key_as_string": "2015-12-27T00:00:00.000Z",
          "key": 1451174400000,
          "doc_count": 0
        },
        {
          "key_as_string": "2015-12-28T00:00:00.000Z",
          "key": 1451260800000,
          "doc_count": 0
        },
...
```

**Comment by MorganPeterson** [comment]
It does, but the 23rd data still does not show up in the the forum data volume chart or in the user timelines.

**Comment by MorganPeterson** [comment]
The error is somewhere in node or in the front end. The dates seems to be offset by one. ie 12/23 is in the chart as 12/22 and 1/12 is 1/11.

**Comment by MorganPeterson** [comment]
The error is happening in the draw function of board.js. When the timeline data is coming in it gets converted to a date object. It appears to be a timezone issue.

**Comment by bkj** [comment]
Ah yeah that makes sense.  I think our timestamps are probably in Eastern
Time, but Elasticsearch is likely treating them as UTC

**Comment by MorganPeterson** [comment]
The easiest way that I found to correct the issue was to force the Date method to stop setting the timezone but showing it a string it couldn't guess at. I replaced '-' with '/' and removed the time stamp and it now just makes a date object based on the actual date passed.
